### PR TITLE
v3 temporary branch

### PR DESCRIPTION
**Pull request by sophiedeziel**
Work to make this branch mergable is tracked in https://github.com/remcoder/gcode-preview/issues/221

This is the PR to track the diff between the temporary `v3.x` branch and `develop`.
All changes in this branch are related to the [refactor](https://github.com/remcoder/gcode-preview/pull/211) to split out parsing/interpreting from `WebGLPreview` and introducing `Job` and `Path` primitives.

This refactor had to be done incrementally because it affected most current features. Each PR addresses a specific feature to bring it to the closest state possible to the v2 behavior. 

The only feature that was scoped out is the highlight of the last layer and segment.

### CODE REVIEW

**Comment by sophiedeziel** [comment]
* **#225** <a href="https://app.graphite.dev/github/pr/remcoder/gcode-preview/225?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 6  dependent PRs ([#220](https://github.com/remcoder/gcode-preview/pull/220) <a href="https://app.graphite.dev/github/pr/remcoder/gcode-preview/220?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#224](https://github.com/remcoder/gcode-preview/pull/224) <a href="https://app.graphite.dev/github/pr/remcoder/gcode-preview/224?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#227](https://github.com/remcoder/gcode-preview/pull/227) <a href="https://app.graphite.dev/github/pr/remcoder/gcode-preview/227?utm_source=stack-comment-icon" target="_blank">Graphite</a> and 3 others) 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sophiedeziel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by remcoder** [comment]
Wow! It's ready! What an amazing achievement! Since we've already discussed many aspects and to not keep you waiting I'll just summarize my first findings based on some black box testing:

- [x] start layer slider doesn't seem to work
- [x] The LineWidth fix stills need to be ported from the v2 branch
- [x] changing the size of the build volume doesn't work (broken in v2 as well. I'll create a separate ticket) (#243)

 But apart from this..... 🎉  **everything Just Works™!** 🎉

**Comment by sophiedeziel** [comment]
>start layer slider doesn't seem to work
>The LineWidth fix stills need to be ported from the v2 branch

I am pretty sure I addressed both recently! Let me see if a commit got lost or if I hallucinated!

**Comment by sophiedeziel** [comment]
✅ Did fix start layer
✅ Ported the lineWidth fix in https://github.com/remcoder/gcode-preview/pull/234 (because I had to implement clipping for lines)
☑️ Build volume fix here: https://github.com/remcoder/gcode-preview/pull/245

**Pull request merged**
