### PR TITLE
Extract out BuildVolume

### PR DESCRIPTION
**Pull request by sophiedeziel**
As explored in https://github.com/remcoder/gcode-preview/pull/169, I've extracted out the build volume to encapsulate the attributes and geometry building.

### CODE REVIEW

**Comment by remcoder** [comment]
I think it's fine for now, separating it out as a util. Eventually we'd want to move to a scheme where we add/remove objects like a build plate to the scene. 

Also it might be better to separate the axes from the build plate, eventually that is.

**Comment by sophiedeziel** [comment]
Agreed, they could all be separated. In a way, I find it elegant to have the build volume in a single object but with different methods to represent it on the scene. They all use the same x,y and z values.

**Comment by remcoder** [comment]
@sophiedeziel this LGTM. Agree to merge?

**Comment by sophiedeziel** [comment]
Yes!

**Pull request merged**
