### PR TITLE
Implement support for G2/G3 arcs

### PR DESCRIPTION
**Pull request by remcoder**
This PR, in response to https://github.com/remcoder/gcode-preview/issues/55,  aims to implement support for G2 and G3 commands to produce arcs.

Following [Marlin](https://marlinfw.org/docs/gcode/G002-G003.html), The output of this would be to create an approximation of the defined arcs using small (~1mm) straight line segments and pass that on to the Three.js renderer. 

image

[This code in npm_gcode_viewer can be used for inspiration](https://github.com/Sindarius/npm_gcodeviewer/blob/main/src/utils.js).

### CODE REVIEW

**Comment by Sindarius** [comment]
I flubbed and probably should have done the work on this here but @RickRyan26 I have a PR setup which fully implements G2/G3 and the I/J params. Tools like ArcWelder are going to utilize both so you have to have both implemented or you can end up with missing points in the gcode which lead to circle artifacts.  There is one issue where the top of the test bench is not fully rendering so feel free to look into that.

Arc benchy
image

Same benchy (you'll see G2/G3)
image

**Comment by remcoder** [comment]
@Sindarius Awesome! Thx a lot for helping out dude!

**Comment by Sindarius** [comment]
Not a problem once he pulls my pr across into his you can grab and test and find that one last issue. My guess is maybe a count is off somewhere but I am not certain. But this will get you close 👍

**Comment by remcoder** [comment]
Super! 
@RickRyan26 I'm already pulling in the changes from both your repo's so don't worry.

**Comment by remcoder** [comment]
@RickRyan26 changes have been pushed to the `feature/arcs` branch for now. Please give it a try. I'll publish a new version on npm soon

**Pull request merged**
