### PR TITLE
added reset view and  set scene background color in launcher

### PR DESCRIPTION
**Pull request by raulodev**
- Added [reset view](https://github.com/remcoder/gcode-preview/commit/7364eec15ab3e3a435a983298e62a482bcef9624)
- added [set scene background color in launcher](https://github.com/remcoder/gcode-preview/commit/f5fa6cfeec6aa03f8e32f0a34b0281ef750e8bad)
- update target and module to ES2020 in tsconfig.json ( I get some errors when i use pnpm with es2015)
- update demo :
    - added button for reset view
    - change background color from gray to white
- some changes in `demo/index.html` make by code formater (Prettier)

### CODE REVIEW

**Comment by remcoder** [comment]
Hi @raulodev, I appreciate your contribution very much!

In order to get your changes merged I suggest the following:
- Strip out the changes that are pure formatting - it helps me focus on the important bits
- make a different PR for the ES2020 change, including an error log or something that allows me to verify both the error _and_ the fix. 
- what's left in this PR would be the reset function & demo changes. These look fine to me, so I'll merge that when this PR is cleaned up.

When you create a PR for the ES2020 change, make sure all the demos are in a working state. I ran the vue-demo and it throws an `Unexpected token`. I find transpile issues hard to debug, so please let me know if the demos run OK for you and what node version you used. 

Again, thanks for your contribution. It's really nice to see people actually care for a small open source project like this 😄 . Let me know if I can help you with something.

cheers

**Comment by remcoder** [comment]
Note that I'm adding the background color to #81.

**Comment by raulodev** [comment]
I like this, great job

image

**Comment by remcoder** [comment]
Hi @raulodev do you still want (some of) these changes to go in? Or can we close it?

**Comment by raulodev** [comment]
@remcoder close it

**Pull request closed without merging**
