### PR TITLE
Introduce Dev mode

### PR DESCRIPTION
**Pull request by sophiedeziel**
# Context
Part of #153 

I started some explorations on how I could implement the dev mode. 

Screenshot 2024-06-01 at 12 42 24

## Approach
The easiest path I found was using the lil-gui library included in Three.js.

There are many advantages to that library:

- No need to add dependencies
- Neat API that allowed me to add controls in very few lines of code
- Built to control attributes, so it's easy to play with them
- No need to style ourselves (but we can if we want)
- Built-in hiearchy that helps organize the information
- Many control types built-in

# Discussion

## Do you think the demo could use the library as well? 
That will simplify the demo code a lot, IMO. We can style the panel so it's prettier for demo purposes.

### CODE REVIEW

**Comment by remcoder** [comment]
Seems like a great choice to use lil-gui. And yes It could be part of the lib, especially since it is based on threejs so it won't add new deps.

**Comment by sophiedeziel** [comment]
That's what I was thinking. Having debug and dev tools helps in the library's development, but also helps development of apps using and interacting with the library.

**Comment by remcoder** [comment]
Totally agree!

**Comment by sophiedeziel** [comment]
That's weird, the preview link does not show the demo mode. I'm not sure if I messed up the branch update or if it's deploying the develop branch. Looking at the source, it looks like develop.

**Comment by sophiedeziel** [comment]
Fixed the preview link in https://github.com/remcoder/gcode-preview/pull/162

**Comment by remcoder** [comment]
Just played with the dev tools. This is sooo useful! Being able to see the # of triangles, or change the camera position. Love it!

Maybe the buttons to store/restore the camera position we talked about should go in there? If possible?

**Comment by sophiedeziel** [comment]
> Maybe the buttons to store/restore the camera position we talked about should go in there? If possible? 

Yes! Entirely possible!!! And so easy!

**Pull request merged**
