### PR TITLE
Add a mode to render extrusion as tubes

### PR DESCRIPTION
**Pull request by sophiedeziel**
As discussed in https://github.com/remcoder/gcode-preview/issues/89, here is a first version of rendering extrusions as tubes.

There are some key differences from the prototype as well as some decisions that I've made. I'm open to feedback and I can revert/adapt them:

1. Travel moves are always lines, not tubes. It helps with visibility and performance
2. The `Vector3` defined in `webgl-preview.ts` conflicted with `Three.js`'s class. I renamed it to `GVector3`. I did not put too much thinking in the name. I thought they came from GCode, so they are GVectors. I you prefer a different name or switch to `Three.js`'s vectors, I'll make the change.
3. I changed how Single Layer mode renders colors for lines AND tubes. It takes the pure colors without changing the brightness. A single layer is about the details and they are much easier to see when the color is an exact match to what was chosen.
4. Rendered tubes don't have the gradient as well. I can change that, especially if https://github.com/remcoder/gcode-preview/issues/85 is implemented.
5. As discussed in the original issue, `TubeGeometry` with a `CatmullRomCurve3` is much more performant than single-cylinder segments. It's prettier as well.
6. I've evaluated that a factor of `2` for the number of tube segments per tube length units is the best balance between performance versus render quality. This could be a variable in the future.
7. `MeshLambertMaterial` is the most performant, but switching to one that offers more options in terms may give us more flexibility in the future. The performance gains are not humanly noticeable with the benchy demo as of right now.
8. I set a tube radius of `0.3`, but it's arbitrary. It could be tied to `lineWidth`, have its own new option, or be calculated based on the slicer's line width or layer height, or a combination of those variables. I'm keeping that for a future PR.

Here is a screenshot of the final result!
Screenshot 2023-12-20 at 7 14 08 PM

### CODE REVIEW

**Comment by remcoder** [comment]
## Feedback on your points

Totally agree on all points. Both on the current choices and what to hold back for later. 

Naming my own type Vector3 was a mistake. The only worry I have is that is inside the .d.ts file, which makes it an exported type. Renaming it can cause consumers to have build failures. I don't consider it to be high-risk or important enough to prevent this though. So let's stay with GVector3 ;-)

Let's not add a gradient here. It was only a cheap way to mimic lighting.

## Finishing up 
So, if I'm not mistaken this might already be the point were the PR can finished, not? You didn't mention any significant TODO's and I don't have any in terms of functionality either.

I'd prefer to make a separate `addTubeLine` (or something) instead of adding cases inside `addLine`. This also removes the need for `forceLine` for travel lines bc it can just use the old addLine as it were.

There's some things like the lighting that are added to the scene but are only needed for realistic rendering.

I spotted a [typo](https://github.com/remcoder/gcode-preview/pull/92/files#diff-8ec787c979ef6cb88e426e798a75cc41d326888eaca61c5f5691b18c5e65c729R51) btw. 

The only 'big' question is how to expose this new behaviour. I think it should be opt-in, do you agree? And the config param to turn it on should be not too prone to typo's so I'd be more in favour of something like `renderTubes` than `realisticExtrusion` ;-) 

## Testing & what were aiming for
Let's also test with at least:
 - a model that is 2-3x the size as a benchy or even bigger
 - a [vase](https://github.com/remcoder/gcode-preview/issues/71)
 
For now, it is OK for this rendering mode to be unusable for a certain domain of large models. As long as it is usable for a reasonable set of models. 

## Guidelines
As for general guidelines, just as an FYI and since you asked for my vision, here are some things that are in the back of my head:

- the library should Just Work for any gcode file that comes out of a slicer.
- CNC compatibility comes second if the choice needs to be made
- the preview should work with a minimum of mandatory config to be set.
- Tweakability comes after that and we need to be careful not to duplicate THREE's api and pass all the params through. 
- Backwards compatibility is important (I think this is how you enable this slow growth of a small OSS project). Both in terms of API and in terms of behaviour. (I think I broke that principe when I introduced customizabe colors but it's an exception). Performance is important because it can easily become a problem. Both slowdowns and memory usage going through the roof have been issues in the past.
- it should in principle work on mobile without modification, for reasonably sized models. 
 
 I'll add these to a more visible document too.

**Comment by remcoder** [comment]
Oh and did I mention you're doing amazing work?.. You're doing amazing work! 😉  🚀

**Comment by sophiedeziel** [comment]
I've implemented all of your suggestion, I agree with them. Thank you for the feedback!

Also, I tried a vase, a file with multiple parts and a large print. As I expected, it takes much longer to render. But it is still in the useable range. It bothers me that it locks the whole tab's operations, I'd like to work on this next. If you are OK with this, I think it should be a follow up PR. 

## The large vase you linked
This one highlights the need for a dynamic tube radius. It renders nicely, but the layer height is obviously larger. Also keeping this for a follow-up PR.

Screenshot 2023-12-22 at 10 45 04 PM

## Multiple parts

Screenshot 2023-12-22 at 10 49 11 PM

## A large print
This one took 9 seconds in average to render.

Screenshot 2023-12-22 at 10 51 15 PM

**Comment by remcoder** [comment]
merry 🎄! (if you're celebrating)

Works great & looks great! The render times are similar for me. (Changing color is actually very fast comparatively.) 

Nice work @sophiedeziel

**Pull request merged**
