### PR TITLE
Add React & Typescript integration demo

### PR DESCRIPTION
**Pull request by Zeng95**
Following on issue https://github.com/remcoder/gcode-preview/issues/43

### CODE REVIEW

**Comment by remcoder** [comment]
Hi @Zeng95 , thx for this PR! It's really nice to have a React example so this is very much appreciated :D

I did run into an issue when I ran `npm run start`:
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "^7.11.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  /Users/remcoder/node_modules/eslint (version: 8.9.0) 
 ```
  
Full reproduction steps:
```
git clone repo
cd react-typescript-demo
npm install
npm run start
```

I can workaround the error by creating a `.env` file with `SKIP_PREFLIGHT_CHECK=true` but I am unsure if this is the best solution as don't have much React knowledge.

What would you advise?

Again thank you very much for this nice React example 👍🏻  😄 

I'll merge the PR with either my fix or your suggestion I you have one.

**Comment by Zeng95** [comment]
> Hi @Zeng95 , thx for this PR! It's really nice to have a React example so this is very much appreciated :D
> 
> I did run into an issue when I ran `npm run start`:
> 
> ```
> There might be a problem with the project dependency tree.
> It is likely not a bug in Create React App, but something you need to fix locally.
> 
> The react-scripts package provided by Create React App requires a dependency:
> 
>   "eslint": "^7.11.0"
> 
> Don't try to install it manually: your package manager does it automatically.
> However, a different version of eslint was detected higher up in the tree:
> 
>   /Users/remcoder/node_modules/eslint (version: 8.9.0) 
> ```
> 
> Full reproduction steps:
> 
> ```
> git clone repo
> cd react-typescript-demo
> npm install
> npm run start
> ```
> 
> I can workaround the error by creating a `.env` file with `SKIP_PREFLIGHT_CHECK=true` but I am unsure if this is the best solution as don't have much React knowledge.
> 
> What would you advise?
> 
> Again thank you very much for this nice React example 👍🏻 😄
> 
> I'll merge the PR with either my fix or your suggestion I you have one.

It looks like you have ESLint installed globally, right?

**Comment by Zeng95** [comment]
The reason that there's an error regarding ESLint is that I'm not using the latest version of react-scripts.

**Comment by Zeng95** [comment]
@remcoder Please use `SKIP_PREFLIGHT_CHECK=true` suggested by the react team https://github.com/facebook/create-react-app/issues/5247#issuecomment-427221678

**Comment by remcoder** [comment]
fixes #43

**Comment by remcoder** [comment]
@Zeng95 Thank you!

**Pull request merged**
